//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 10:00:40 AM SGT 
//


package nl.connekt.bison.psa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang3.builder.ToStringBuilder;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}quaycode"/&gt;
 *         &lt;element ref="{}userstopcodes"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quaycode",
    "userstopcodes"
})
@XmlRootElement(name = "quay")
public class Quay {

    @XmlElement(required = true)
    protected String quaycode;
    @XmlElement(required = true)
    protected Userstopcodes userstopcodes;

    /**
     * Gets the value of the quaycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuaycode() {
        return quaycode;
    }

    /**
     * Sets the value of the quaycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuaycode(String value) {
        this.quaycode = value;
    }

    /**
     * Gets the value of the userstopcodes property.
     * 
     * @return
     *     possible object is
     *     {@link Userstopcodes }
     *     
     */
    public Userstopcodes getUserstopcodes() {
        return userstopcodes;
    }

    /**
     * Sets the value of the userstopcodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Userstopcodes }
     *     
     */
    public void setUserstopcodes(Userstopcodes value) {
        this.userstopcodes = value;
    }

    public Quay withQuaycode(String value) {
        setQuaycode(value);
        return this;
    }

    public Quay withUserstopcodes(Userstopcodes value) {
        setUserstopcodes(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
