//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 10:00:40 AM SGT 
//


package nl.connekt.bison.psa;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang3.builder.ToStringBuilder;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}userstopcodedata" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userstopcodedata"
})
@XmlRootElement(name = "userstopcodes")
public class Userstopcodes {

    @XmlElement(required = true)
    protected List<Userstopcodedata> userstopcodedata;

    /**
     * Gets the value of the userstopcodedata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userstopcodedata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserstopcodedata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Userstopcodedata }
     * 
     * 
     */
    public List<Userstopcodedata> getUserstopcodedata() {
        if (userstopcodedata == null) {
            userstopcodedata = new ArrayList<Userstopcodedata>();
        }
        return this.userstopcodedata;
    }

    public Userstopcodes withUserstopcodedata(Userstopcodedata... values) {
        if (values!= null) {
            for (Userstopcodedata value: values) {
                getUserstopcodedata().add(value);
            }
        }
        return this;
    }

    public Userstopcodes withUserstopcodedata(Collection<Userstopcodedata> values) {
        if (values!= null) {
            getUserstopcodedata().addAll(values);
        }
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
