//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.27 at 10:00:40 AM SGT 
//


package nl.connekt.bison.psa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang3.builder.ToStringBuilder;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}dataownercode"/&gt;
 *         &lt;element ref="{}userstopcode"/&gt;
 *         &lt;element ref="{}validfrom"/&gt;
 *         &lt;element ref="{}validthru" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataownercode",
    "userstopcode",
    "validfrom",
    "validthru"
})
@XmlRootElement(name = "userstopcodedata")
public class Userstopcodedata {

    @XmlElement(required = true)
    protected String dataownercode;
    @XmlElement(required = true)
    protected String userstopcode;
    @XmlElement(required = true)
    protected String validfrom;
    protected String validthru;

    /**
     * Gets the value of the dataownercode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataownercode() {
        return dataownercode;
    }

    /**
     * Sets the value of the dataownercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataownercode(String value) {
        this.dataownercode = value;
    }

    /**
     * Gets the value of the userstopcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserstopcode() {
        return userstopcode;
    }

    /**
     * Sets the value of the userstopcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserstopcode(String value) {
        this.userstopcode = value;
    }

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidfrom(String value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the validthru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidthru() {
        return validthru;
    }

    /**
     * Sets the value of the validthru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidthru(String value) {
        this.validthru = value;
    }

    public Userstopcodedata withDataownercode(String value) {
        setDataownercode(value);
        return this;
    }

    public Userstopcodedata withUserstopcode(String value) {
        setUserstopcode(value);
        return this;
    }

    public Userstopcodedata withValidfrom(String value) {
        setValidfrom(value);
        return this;
    }

    public Userstopcodedata withValidthru(String value) {
        setValidthru(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
