//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bison.connekt.nl/tmi8/chb/core")
package nl.connekt.bison.tmi8.chb.core;
