//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}daowcode"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}daowname"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}daowtype"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "daowcode",
    "daowname",
    "daowtype"
})
@XmlRootElement(name = "dataowner")
public class Dataowner {

    @XmlElement(required = true)
    protected String daowcode;
    @XmlElement(required = true)
    protected String daowname;
    @XmlElement(required = true)
    protected String daowtype;

    /**
     * Gets the value of the daowcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaowcode() {
        return daowcode;
    }

    /**
     * Sets the value of the daowcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaowcode(String value) {
        this.daowcode = value;
    }

    /**
     * Gets the value of the daowname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaowname() {
        return daowname;
    }

    /**
     * Sets the value of the daowname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaowname(String value) {
        this.daowname = value;
    }

    /**
     * Gets the value of the daowtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaowtype() {
        return daowtype;
    }

    /**
     * Sets the value of the daowtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaowtype(String value) {
        this.daowtype = value;
    }

    public Dataowner withDaowcode(String value) {
        setDaowcode(value);
        return this;
    }

    public Dataowner withDaowname(String value) {
        setDaowname(value);
        return this;
    }

    public Dataowner withDaowtype(String value) {
        setDaowtype(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
