//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stopplaces" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}places" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}dataowners" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stopplaces",
    "places",
    "dataowners"
})
@XmlRootElement(name = "export")
public class Export {

    protected List<Stopplaces> stopplaces;
    protected List<Places> places;
    protected List<Dataowners> dataowners;

    /**
     * Gets the value of the stopplaces property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stopplaces property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStopplaces().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stopplaces }
     * 
     * 
     */
    public List<Stopplaces> getStopplaces() {
        if (stopplaces == null) {
            stopplaces = new ArrayList<Stopplaces>();
        }
        return this.stopplaces;
    }

    /**
     * Gets the value of the places property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the places property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlaces().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Places }
     * 
     * 
     */
    public List<Places> getPlaces() {
        if (places == null) {
            places = new ArrayList<Places>();
        }
        return this.places;
    }

    /**
     * Gets the value of the dataowners property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataowners property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataowners().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dataowners }
     * 
     * 
     */
    public List<Dataowners> getDataowners() {
        if (dataowners == null) {
            dataowners = new ArrayList<Dataowners>();
        }
        return this.dataowners;
    }

    public Export withStopplaces(Stopplaces... values) {
        if (values!= null) {
            for (Stopplaces value: values) {
                getStopplaces().add(value);
            }
        }
        return this;
    }

    public Export withStopplaces(Collection<Stopplaces> values) {
        if (values!= null) {
            getStopplaces().addAll(values);
        }
        return this;
    }

    public Export withPlaces(Places... values) {
        if (values!= null) {
            for (Places value: values) {
                getPlaces().add(value);
            }
        }
        return this;
    }

    public Export withPlaces(Collection<Places> values) {
        if (values!= null) {
            getPlaces().addAll(values);
        }
        return this;
    }

    public Export withDataowners(Dataowners... values) {
        if (values!= null) {
            for (Dataowners value: values) {
                getDataowners().add(value);
            }
        }
        return this;
    }

    public Export withDataowners(Collection<Dataowners> values) {
        if (values!= null) {
            getDataowners().addAll(values);
        }
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
