//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.time.ZonedDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import com.maestronic.gtfs.util.ZonedDateTimeISO8601XmlAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ID"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}daowcode"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}validfrom"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}placecode"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}publicname"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}town"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}iconuri" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}description" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "daowcode",
    "validfrom",
    "placecode",
    "publicname",
    "town",
    "iconuri",
    "mutationdate",
    "description"
})
@XmlRootElement(name = "place")
public class Place {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(required = true)
    protected String daowcode;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime validfrom;
    @XmlElement(required = true)
    protected String placecode;
    @XmlElement(required = true)
    protected String publicname;
    @XmlElement(required = true)
    protected String town;
    protected String iconuri;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime mutationdate;
    protected String description;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the daowcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaowcode() {
        return daowcode;
    }

    /**
     * Sets the value of the daowcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaowcode(String value) {
        this.daowcode = value;
    }

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidfrom(ZonedDateTime value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the placecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlacecode() {
        return placecode;
    }

    /**
     * Sets the value of the placecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlacecode(String value) {
        this.placecode = value;
    }

    /**
     * Gets the value of the publicname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicname() {
        return publicname;
    }

    /**
     * Sets the value of the publicname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicname(String value) {
        this.publicname = value;
    }

    /**
     * Gets the value of the town property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTown() {
        return town;
    }

    /**
     * Sets the value of the town property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTown(String value) {
        this.town = value;
    }

    /**
     * Gets the value of the iconuri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconuri() {
        return iconuri;
    }

    /**
     * Sets the value of the iconuri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconuri(String value) {
        this.iconuri = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(ZonedDateTime value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    public Place withID(String value) {
        setID(value);
        return this;
    }

    public Place withDaowcode(String value) {
        setDaowcode(value);
        return this;
    }

    public Place withValidfrom(ZonedDateTime value) {
        setValidfrom(value);
        return this;
    }

    public Place withPlacecode(String value) {
        setPlacecode(value);
        return this;
    }

    public Place withPublicname(String value) {
        setPublicname(value);
        return this;
    }

    public Place withTown(String value) {
        setTown(value);
        return this;
    }

    public Place withIconuri(String value) {
        setIconuri(value);
        return this;
    }

    public Place withMutationdate(ZonedDateTime value) {
        setMutationdate(value);
        return this;
    }

    public Place withDescription(String value) {
        setDescription(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
