//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.time.ZonedDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import com.maestronic.gtfs.util.ZonedDateTimeISO8601XmlAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}validfrom"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}roadcode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}hectometersign" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}greenstop" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}liftedbicyclepath" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validfrom",
    "mutationdate",
    "roadcode",
    "hectometersign",
    "greenstop",
    "liftedbicyclepath"
})
@XmlRootElement(name = "quayextraattributes")
public class Quayextraattributes {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime validfrom;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime mutationdate;
    protected String roadcode;
    protected String hectometersign;
    protected Boolean greenstop;
    protected Boolean liftedbicyclepath;

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidfrom(ZonedDateTime value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(ZonedDateTime value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the roadcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadcode() {
        return roadcode;
    }

    /**
     * Sets the value of the roadcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadcode(String value) {
        this.roadcode = value;
    }

    /**
     * Gets the value of the hectometersign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHectometersign() {
        return hectometersign;
    }

    /**
     * Sets the value of the hectometersign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHectometersign(String value) {
        this.hectometersign = value;
    }

    /**
     * Gets the value of the greenstop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGreenstop() {
        return greenstop;
    }

    /**
     * Sets the value of the greenstop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGreenstop(Boolean value) {
        this.greenstop = value;
    }

    /**
     * Gets the value of the liftedbicyclepath property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLiftedbicyclepath() {
        return liftedbicyclepath;
    }

    /**
     * Sets the value of the liftedbicyclepath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLiftedbicyclepath(Boolean value) {
        this.liftedbicyclepath = value;
    }

    public Quayextraattributes withValidfrom(ZonedDateTime value) {
        setValidfrom(value);
        return this;
    }

    public Quayextraattributes withMutationdate(ZonedDateTime value) {
        setMutationdate(value);
        return this;
    }

    public Quayextraattributes withRoadcode(String value) {
        setRoadcode(value);
        return this;
    }

    public Quayextraattributes withHectometersign(String value) {
        setHectometersign(value);
        return this;
    }

    public Quayextraattributes withGreenstop(Boolean value) {
        setGreenstop(value);
        return this;
    }

    public Quayextraattributes withLiftedbicyclepath(Boolean value) {
        setLiftedbicyclepath(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
