//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.time.ZonedDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import com.maestronic.gtfs.util.ZonedDateTimeISO8601XmlAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayimagedate"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayimageurl"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayimagedescription"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quayimagedate",
    "quayimageurl",
    "quayimagedescription",
    "mutationdate"
})
@XmlRootElement(name = "quayphotodata")
public class Quayphotodata {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime quayimagedate;
    @XmlElement(required = true)
    protected String quayimageurl;
    @XmlElement(required = true)
    protected String quayimagedescription;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime mutationdate;

    /**
     * Gets the value of the quayimagedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getQuayimagedate() {
        return quayimagedate;
    }

    /**
     * Sets the value of the quayimagedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuayimagedate(ZonedDateTime value) {
        this.quayimagedate = value;
    }

    /**
     * Gets the value of the quayimageurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuayimageurl() {
        return quayimageurl;
    }

    /**
     * Sets the value of the quayimageurl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuayimageurl(String value) {
        this.quayimageurl = value;
    }

    /**
     * Gets the value of the quayimagedescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuayimagedescription() {
        return quayimagedescription;
    }

    /**
     * Sets the value of the quayimagedescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuayimagedescription(String value) {
        this.quayimagedescription = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(ZonedDateTime value) {
        this.mutationdate = value;
    }

    public Quayphotodata withQuayimagedate(ZonedDateTime value) {
        setQuayimagedate(value);
        return this;
    }

    public Quayphotodata withQuayimageurl(String value) {
        setQuayimageurl(value);
        return this;
    }

    public Quayphotodata withQuayimagedescription(String value) {
        setQuayimagedescription(value);
        return this;
    }

    public Quayphotodata withMutationdate(ZonedDateTime value) {
        setMutationdate(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
