//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import com.maestronic.gtfs.util.ZonedDateTimeISO8601XmlAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ID"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quaycode"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}validfrom"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quaytypedata"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quaytransportmodes"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quaystatusdata"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quaylocationdata"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quaybearing"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayvisuallyaccessible"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quaydisabledaccessible" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stopobjectcode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stopinternalcode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stopinternalname" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}parentquaycode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}onlygetout" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quaymunicipality" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayowner" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayconcessionprovider" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quaynamedata" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayaccessibilityadaptions" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayfacilities" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayremarks" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayextraattributes" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayphotos" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "quaycode",
    "validfrom",
    "quaytypedata",
    "quaytransportmodes",
    "quaystatusdata",
    "quaylocationdata",
    "quaybearing",
    "quayvisuallyaccessible",
    "quaydisabledaccessible",
    "mutationdate",
    "stopobjectcode",
    "stopinternalcode",
    "stopinternalname",
    "parentquaycode",
    "onlygetout",
    "quaymunicipality",
    "quayowner",
    "quayconcessionprovider",
    "quaynamedata",
    "quayaccessibilityadaptions",
    "quayfacilities",
    "quayremarks",
    "quayextraattributes",
    "quayphotos"
})
@XmlRootElement(name = "quay")
public class Quay {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(required = true)
    protected String quaycode;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime validfrom;
    @XmlElement(required = true)
    protected Quaytypedata quaytypedata;
    @XmlElement(required = true)
    protected Quaytransportmodes quaytransportmodes;
    @XmlElement(required = true)
    protected Quaystatusdata quaystatusdata;
    @XmlElement(required = true)
    protected Quaylocationdata quaylocationdata;
    @XmlElement(required = true)
    protected Quaybearing quaybearing;
    @XmlElement(required = true)
    protected Quayvisuallyaccessible quayvisuallyaccessible;
    @XmlElement(required = true)
    protected List<Quaydisabledaccessible> quaydisabledaccessible;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime mutationdate;
    protected String stopobjectcode;
    protected String stopinternalcode;
    protected String stopinternalname;
    protected String parentquaycode;
    protected Boolean onlygetout;
    protected Quaymunicipality quaymunicipality;
    protected Quayowner quayowner;
    protected Quayconcessionprovider quayconcessionprovider;
    protected Quaynamedata quaynamedata;
    protected Quayaccessibilityadaptions quayaccessibilityadaptions;
    protected Quayfacilities quayfacilities;
    protected Quayremarks quayremarks;
    protected Quayextraattributes quayextraattributes;
    protected Quayphotos quayphotos;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the quaycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuaycode() {
        return quaycode;
    }

    /**
     * Sets the value of the quaycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuaycode(String value) {
        this.quaycode = value;
    }

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidfrom(ZonedDateTime value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the quaytypedata property.
     * 
     * @return
     *     possible object is
     *     {@link Quaytypedata }
     *     
     */
    public Quaytypedata getQuaytypedata() {
        return quaytypedata;
    }

    /**
     * Sets the value of the quaytypedata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaytypedata }
     *     
     */
    public void setQuaytypedata(Quaytypedata value) {
        this.quaytypedata = value;
    }

    /**
     * Gets the value of the quaytransportmodes property.
     * 
     * @return
     *     possible object is
     *     {@link Quaytransportmodes }
     *     
     */
    public Quaytransportmodes getQuaytransportmodes() {
        return quaytransportmodes;
    }

    /**
     * Sets the value of the quaytransportmodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaytransportmodes }
     *     
     */
    public void setQuaytransportmodes(Quaytransportmodes value) {
        this.quaytransportmodes = value;
    }

    /**
     * Gets the value of the quaystatusdata property.
     * 
     * @return
     *     possible object is
     *     {@link Quaystatusdata }
     *     
     */
    public Quaystatusdata getQuaystatusdata() {
        return quaystatusdata;
    }

    /**
     * Sets the value of the quaystatusdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaystatusdata }
     *     
     */
    public void setQuaystatusdata(Quaystatusdata value) {
        this.quaystatusdata = value;
    }

    /**
     * Gets the value of the quaylocationdata property.
     * 
     * @return
     *     possible object is
     *     {@link Quaylocationdata }
     *     
     */
    public Quaylocationdata getQuaylocationdata() {
        return quaylocationdata;
    }

    /**
     * Sets the value of the quaylocationdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaylocationdata }
     *     
     */
    public void setQuaylocationdata(Quaylocationdata value) {
        this.quaylocationdata = value;
    }

    /**
     * Gets the value of the quaybearing property.
     * 
     * @return
     *     possible object is
     *     {@link Quaybearing }
     *     
     */
    public Quaybearing getQuaybearing() {
        return quaybearing;
    }

    /**
     * Sets the value of the quaybearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaybearing }
     *     
     */
    public void setQuaybearing(Quaybearing value) {
        this.quaybearing = value;
    }

    /**
     * Gets the value of the quayvisuallyaccessible property.
     * 
     * @return
     *     possible object is
     *     {@link Quayvisuallyaccessible }
     *     
     */
    public Quayvisuallyaccessible getQuayvisuallyaccessible() {
        return quayvisuallyaccessible;
    }

    /**
     * Sets the value of the quayvisuallyaccessible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayvisuallyaccessible }
     *     
     */
    public void setQuayvisuallyaccessible(Quayvisuallyaccessible value) {
        this.quayvisuallyaccessible = value;
    }

    /**
     * Gets the value of the quaydisabledaccessible property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quaydisabledaccessible property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuaydisabledaccessible().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Quaydisabledaccessible }
     * 
     * 
     */
    public List<Quaydisabledaccessible> getQuaydisabledaccessible() {
        if (quaydisabledaccessible == null) {
            quaydisabledaccessible = new ArrayList<Quaydisabledaccessible>();
        }
        return this.quaydisabledaccessible;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(ZonedDateTime value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the stopobjectcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopobjectcode() {
        return stopobjectcode;
    }

    /**
     * Sets the value of the stopobjectcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopobjectcode(String value) {
        this.stopobjectcode = value;
    }

    /**
     * Gets the value of the stopinternalcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopinternalcode() {
        return stopinternalcode;
    }

    /**
     * Sets the value of the stopinternalcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopinternalcode(String value) {
        this.stopinternalcode = value;
    }

    /**
     * Gets the value of the stopinternalname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopinternalname() {
        return stopinternalname;
    }

    /**
     * Sets the value of the stopinternalname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopinternalname(String value) {
        this.stopinternalname = value;
    }

    /**
     * Gets the value of the parentquaycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentquaycode() {
        return parentquaycode;
    }

    /**
     * Sets the value of the parentquaycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentquaycode(String value) {
        this.parentquaycode = value;
    }

    /**
     * Gets the value of the onlygetout property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnlygetout() {
        return onlygetout;
    }

    /**
     * Sets the value of the onlygetout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnlygetout(Boolean value) {
        this.onlygetout = value;
    }

    /**
     * Gets the value of the quaymunicipality property.
     * 
     * @return
     *     possible object is
     *     {@link Quaymunicipality }
     *     
     */
    public Quaymunicipality getQuaymunicipality() {
        return quaymunicipality;
    }

    /**
     * Sets the value of the quaymunicipality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaymunicipality }
     *     
     */
    public void setQuaymunicipality(Quaymunicipality value) {
        this.quaymunicipality = value;
    }

    /**
     * Gets the value of the quayowner property.
     * 
     * @return
     *     possible object is
     *     {@link Quayowner }
     *     
     */
    public Quayowner getQuayowner() {
        return quayowner;
    }

    /**
     * Sets the value of the quayowner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayowner }
     *     
     */
    public void setQuayowner(Quayowner value) {
        this.quayowner = value;
    }

    /**
     * Gets the value of the quayconcessionprovider property.
     * 
     * @return
     *     possible object is
     *     {@link Quayconcessionprovider }
     *     
     */
    public Quayconcessionprovider getQuayconcessionprovider() {
        return quayconcessionprovider;
    }

    /**
     * Sets the value of the quayconcessionprovider property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayconcessionprovider }
     *     
     */
    public void setQuayconcessionprovider(Quayconcessionprovider value) {
        this.quayconcessionprovider = value;
    }

    /**
     * Gets the value of the quaynamedata property.
     * 
     * @return
     *     possible object is
     *     {@link Quaynamedata }
     *     
     */
    public Quaynamedata getQuaynamedata() {
        return quaynamedata;
    }

    /**
     * Sets the value of the quaynamedata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaynamedata }
     *     
     */
    public void setQuaynamedata(Quaynamedata value) {
        this.quaynamedata = value;
    }

    /**
     * Gets the value of the quayaccessibilityadaptions property.
     * 
     * @return
     *     possible object is
     *     {@link Quayaccessibilityadaptions }
     *     
     */
    public Quayaccessibilityadaptions getQuayaccessibilityadaptions() {
        return quayaccessibilityadaptions;
    }

    /**
     * Sets the value of the quayaccessibilityadaptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayaccessibilityadaptions }
     *     
     */
    public void setQuayaccessibilityadaptions(Quayaccessibilityadaptions value) {
        this.quayaccessibilityadaptions = value;
    }

    /**
     * Gets the value of the quayfacilities property.
     * 
     * @return
     *     possible object is
     *     {@link Quayfacilities }
     *     
     */
    public Quayfacilities getQuayfacilities() {
        return quayfacilities;
    }

    /**
     * Sets the value of the quayfacilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayfacilities }
     *     
     */
    public void setQuayfacilities(Quayfacilities value) {
        this.quayfacilities = value;
    }

    /**
     * Gets the value of the quayremarks property.
     * 
     * @return
     *     possible object is
     *     {@link Quayremarks }
     *     
     */
    public Quayremarks getQuayremarks() {
        return quayremarks;
    }

    /**
     * Sets the value of the quayremarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayremarks }
     *     
     */
    public void setQuayremarks(Quayremarks value) {
        this.quayremarks = value;
    }

    /**
     * Gets the value of the quayextraattributes property.
     * 
     * @return
     *     possible object is
     *     {@link Quayextraattributes }
     *     
     */
    public Quayextraattributes getQuayextraattributes() {
        return quayextraattributes;
    }

    /**
     * Sets the value of the quayextraattributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayextraattributes }
     *     
     */
    public void setQuayextraattributes(Quayextraattributes value) {
        this.quayextraattributes = value;
    }

    /**
     * Gets the value of the quayphotos property.
     * 
     * @return
     *     possible object is
     *     {@link Quayphotos }
     *     
     */
    public Quayphotos getQuayphotos() {
        return quayphotos;
    }

    /**
     * Sets the value of the quayphotos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayphotos }
     *     
     */
    public void setQuayphotos(Quayphotos value) {
        this.quayphotos = value;
    }

    public Quay withID(String value) {
        setID(value);
        return this;
    }

    public Quay withQuaycode(String value) {
        setQuaycode(value);
        return this;
    }

    public Quay withValidfrom(ZonedDateTime value) {
        setValidfrom(value);
        return this;
    }

    public Quay withQuaytypedata(Quaytypedata value) {
        setQuaytypedata(value);
        return this;
    }

    public Quay withQuaytransportmodes(Quaytransportmodes value) {
        setQuaytransportmodes(value);
        return this;
    }

    public Quay withQuaystatusdata(Quaystatusdata value) {
        setQuaystatusdata(value);
        return this;
    }

    public Quay withQuaylocationdata(Quaylocationdata value) {
        setQuaylocationdata(value);
        return this;
    }

    public Quay withQuaybearing(Quaybearing value) {
        setQuaybearing(value);
        return this;
    }

    public Quay withQuayvisuallyaccessible(Quayvisuallyaccessible value) {
        setQuayvisuallyaccessible(value);
        return this;
    }

    public Quay withQuaydisabledaccessible(Quaydisabledaccessible... values) {
        if (values!= null) {
            for (Quaydisabledaccessible value: values) {
                getQuaydisabledaccessible().add(value);
            }
        }
        return this;
    }

    public Quay withQuaydisabledaccessible(Collection<Quaydisabledaccessible> values) {
        if (values!= null) {
            getQuaydisabledaccessible().addAll(values);
        }
        return this;
    }

    public Quay withMutationdate(ZonedDateTime value) {
        setMutationdate(value);
        return this;
    }

    public Quay withStopobjectcode(String value) {
        setStopobjectcode(value);
        return this;
    }

    public Quay withStopinternalcode(String value) {
        setStopinternalcode(value);
        return this;
    }

    public Quay withStopinternalname(String value) {
        setStopinternalname(value);
        return this;
    }

    public Quay withParentquaycode(String value) {
        setParentquaycode(value);
        return this;
    }

    public Quay withOnlygetout(Boolean value) {
        setOnlygetout(value);
        return this;
    }

    public Quay withQuaymunicipality(Quaymunicipality value) {
        setQuaymunicipality(value);
        return this;
    }

    public Quay withQuayowner(Quayowner value) {
        setQuayowner(value);
        return this;
    }

    public Quay withQuayconcessionprovider(Quayconcessionprovider value) {
        setQuayconcessionprovider(value);
        return this;
    }

    public Quay withQuaynamedata(Quaynamedata value) {
        setQuaynamedata(value);
        return this;
    }

    public Quay withQuayaccessibilityadaptions(Quayaccessibilityadaptions value) {
        setQuayaccessibilityadaptions(value);
        return this;
    }

    public Quay withQuayfacilities(Quayfacilities value) {
        setQuayfacilities(value);
        return this;
    }

    public Quay withQuayremarks(Quayremarks value) {
        setQuayremarks(value);
        return this;
    }

    public Quay withQuayextraattributes(Quayextraattributes value) {
        setQuayextraattributes(value);
        return this;
    }

    public Quay withQuayphotos(Quayphotos value) {
        setQuayphotos(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
