//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import com.maestronic.gtfs.util.ZonedDateTimeISO8601XmlAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}validfrom"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}quayshapetype"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}baylength"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}markedkerb"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}lift"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}guidelines"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}groundsurfaceindicator"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stopplaceaccessroute"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}embaymentwidth" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}bayentranceangles" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}bayexitangles" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}kerbheight" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}boardingpositionwidth" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}alightingpositionwidth" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}liftedpartlength" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}narrowestpassagewidth" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}fulllengthguideline" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}guidelinestopplaceconnection" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}tactilegroundsurfaceindicator" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ramp" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ramplength" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}heightwithenvironment" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}rampwidth" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validfrom",
    "quayshapetype",
    "baylength",
    "markedkerb",
    "lift",
    "guidelines",
    "groundsurfaceindicator",
    "stopplaceaccessroute",
    "mutationdate",
    "embaymentwidth",
    "bayentranceangles",
    "bayexitangles",
    "kerbheight",
    "boardingpositionwidth",
    "alightingpositionwidth",
    "liftedpartlength",
    "narrowestpassagewidth",
    "fulllengthguideline",
    "guidelinestopplaceconnection",
    "tactilegroundsurfaceindicator",
    "ramp",
    "ramplength",
    "heightwithenvironment",
    "rampwidth"
})
@XmlRootElement(name = "quayaccessibilityadaptions")
public class Quayaccessibilityadaptions {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime validfrom;
    @XmlElement(required = true)
    protected String quayshapetype;
    @XmlElement(required = true)
    protected BigDecimal baylength;
    protected boolean markedkerb;
    protected boolean lift;
    protected boolean guidelines;
    protected boolean groundsurfaceindicator;
    protected boolean stopplaceaccessroute;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime mutationdate;
    protected BigDecimal embaymentwidth;
    protected BigDecimal bayentranceangles;
    protected BigDecimal bayexitangles;
    protected BigDecimal kerbheight;
    protected BigDecimal boardingpositionwidth;
    protected BigDecimal alightingpositionwidth;
    protected BigDecimal liftedpartlength;
    protected BigDecimal narrowestpassagewidth;
    protected Boolean fulllengthguideline;
    protected Boolean guidelinestopplaceconnection;
    protected Boolean tactilegroundsurfaceindicator;
    protected Boolean ramp;
    protected BigDecimal ramplength;
    protected BigDecimal heightwithenvironment;
    protected BigDecimal rampwidth;

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidfrom(ZonedDateTime value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the quayshapetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuayshapetype() {
        return quayshapetype;
    }

    /**
     * Sets the value of the quayshapetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuayshapetype(String value) {
        this.quayshapetype = value;
    }

    /**
     * Gets the value of the baylength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaylength() {
        return baylength;
    }

    /**
     * Sets the value of the baylength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaylength(BigDecimal value) {
        this.baylength = value;
    }

    /**
     * Gets the value of the markedkerb property.
     * 
     */
    public boolean isMarkedkerb() {
        return markedkerb;
    }

    /**
     * Sets the value of the markedkerb property.
     * 
     */
    public void setMarkedkerb(boolean value) {
        this.markedkerb = value;
    }

    /**
     * Gets the value of the lift property.
     * 
     */
    public boolean isLift() {
        return lift;
    }

    /**
     * Sets the value of the lift property.
     * 
     */
    public void setLift(boolean value) {
        this.lift = value;
    }

    /**
     * Gets the value of the guidelines property.
     * 
     */
    public boolean isGuidelines() {
        return guidelines;
    }

    /**
     * Sets the value of the guidelines property.
     * 
     */
    public void setGuidelines(boolean value) {
        this.guidelines = value;
    }

    /**
     * Gets the value of the groundsurfaceindicator property.
     * 
     */
    public boolean isGroundsurfaceindicator() {
        return groundsurfaceindicator;
    }

    /**
     * Sets the value of the groundsurfaceindicator property.
     * 
     */
    public void setGroundsurfaceindicator(boolean value) {
        this.groundsurfaceindicator = value;
    }

    /**
     * Gets the value of the stopplaceaccessroute property.
     * 
     */
    public boolean isStopplaceaccessroute() {
        return stopplaceaccessroute;
    }

    /**
     * Sets the value of the stopplaceaccessroute property.
     * 
     */
    public void setStopplaceaccessroute(boolean value) {
        this.stopplaceaccessroute = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(ZonedDateTime value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the embaymentwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmbaymentwidth() {
        return embaymentwidth;
    }

    /**
     * Sets the value of the embaymentwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmbaymentwidth(BigDecimal value) {
        this.embaymentwidth = value;
    }

    /**
     * Gets the value of the bayentranceangles property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBayentranceangles() {
        return bayentranceangles;
    }

    /**
     * Sets the value of the bayentranceangles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBayentranceangles(BigDecimal value) {
        this.bayentranceangles = value;
    }

    /**
     * Gets the value of the bayexitangles property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBayexitangles() {
        return bayexitangles;
    }

    /**
     * Sets the value of the bayexitangles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBayexitangles(BigDecimal value) {
        this.bayexitangles = value;
    }

    /**
     * Gets the value of the kerbheight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKerbheight() {
        return kerbheight;
    }

    /**
     * Sets the value of the kerbheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKerbheight(BigDecimal value) {
        this.kerbheight = value;
    }

    /**
     * Gets the value of the boardingpositionwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBoardingpositionwidth() {
        return boardingpositionwidth;
    }

    /**
     * Sets the value of the boardingpositionwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBoardingpositionwidth(BigDecimal value) {
        this.boardingpositionwidth = value;
    }

    /**
     * Gets the value of the alightingpositionwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAlightingpositionwidth() {
        return alightingpositionwidth;
    }

    /**
     * Sets the value of the alightingpositionwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAlightingpositionwidth(BigDecimal value) {
        this.alightingpositionwidth = value;
    }

    /**
     * Gets the value of the liftedpartlength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLiftedpartlength() {
        return liftedpartlength;
    }

    /**
     * Sets the value of the liftedpartlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLiftedpartlength(BigDecimal value) {
        this.liftedpartlength = value;
    }

    /**
     * Gets the value of the narrowestpassagewidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNarrowestpassagewidth() {
        return narrowestpassagewidth;
    }

    /**
     * Sets the value of the narrowestpassagewidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNarrowestpassagewidth(BigDecimal value) {
        this.narrowestpassagewidth = value;
    }

    /**
     * Gets the value of the fulllengthguideline property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFulllengthguideline() {
        return fulllengthguideline;
    }

    /**
     * Sets the value of the fulllengthguideline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFulllengthguideline(Boolean value) {
        this.fulllengthguideline = value;
    }

    /**
     * Gets the value of the guidelinestopplaceconnection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGuidelinestopplaceconnection() {
        return guidelinestopplaceconnection;
    }

    /**
     * Sets the value of the guidelinestopplaceconnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGuidelinestopplaceconnection(Boolean value) {
        this.guidelinestopplaceconnection = value;
    }

    /**
     * Gets the value of the tactilegroundsurfaceindicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTactilegroundsurfaceindicator() {
        return tactilegroundsurfaceindicator;
    }

    /**
     * Sets the value of the tactilegroundsurfaceindicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTactilegroundsurfaceindicator(Boolean value) {
        this.tactilegroundsurfaceindicator = value;
    }

    /**
     * Gets the value of the ramp property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRamp() {
        return ramp;
    }

    /**
     * Sets the value of the ramp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRamp(Boolean value) {
        this.ramp = value;
    }

    /**
     * Gets the value of the ramplength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRamplength() {
        return ramplength;
    }

    /**
     * Sets the value of the ramplength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRamplength(BigDecimal value) {
        this.ramplength = value;
    }

    /**
     * Gets the value of the heightwithenvironment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeightwithenvironment() {
        return heightwithenvironment;
    }

    /**
     * Sets the value of the heightwithenvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeightwithenvironment(BigDecimal value) {
        this.heightwithenvironment = value;
    }

    /**
     * Gets the value of the rampwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRampwidth() {
        return rampwidth;
    }

    /**
     * Sets the value of the rampwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRampwidth(BigDecimal value) {
        this.rampwidth = value;
    }

    public Quayaccessibilityadaptions withValidfrom(ZonedDateTime value) {
        setValidfrom(value);
        return this;
    }

    public Quayaccessibilityadaptions withQuayshapetype(String value) {
        setQuayshapetype(value);
        return this;
    }

    public Quayaccessibilityadaptions withBaylength(BigDecimal value) {
        setBaylength(value);
        return this;
    }

    public Quayaccessibilityadaptions withMarkedkerb(boolean value) {
        setMarkedkerb(value);
        return this;
    }

    public Quayaccessibilityadaptions withLift(boolean value) {
        setLift(value);
        return this;
    }

    public Quayaccessibilityadaptions withGuidelines(boolean value) {
        setGuidelines(value);
        return this;
    }

    public Quayaccessibilityadaptions withGroundsurfaceindicator(boolean value) {
        setGroundsurfaceindicator(value);
        return this;
    }

    public Quayaccessibilityadaptions withStopplaceaccessroute(boolean value) {
        setStopplaceaccessroute(value);
        return this;
    }

    public Quayaccessibilityadaptions withMutationdate(ZonedDateTime value) {
        setMutationdate(value);
        return this;
    }

    public Quayaccessibilityadaptions withEmbaymentwidth(BigDecimal value) {
        setEmbaymentwidth(value);
        return this;
    }

    public Quayaccessibilityadaptions withBayentranceangles(BigDecimal value) {
        setBayentranceangles(value);
        return this;
    }

    public Quayaccessibilityadaptions withBayexitangles(BigDecimal value) {
        setBayexitangles(value);
        return this;
    }

    public Quayaccessibilityadaptions withKerbheight(BigDecimal value) {
        setKerbheight(value);
        return this;
    }

    public Quayaccessibilityadaptions withBoardingpositionwidth(BigDecimal value) {
        setBoardingpositionwidth(value);
        return this;
    }

    public Quayaccessibilityadaptions withAlightingpositionwidth(BigDecimal value) {
        setAlightingpositionwidth(value);
        return this;
    }

    public Quayaccessibilityadaptions withLiftedpartlength(BigDecimal value) {
        setLiftedpartlength(value);
        return this;
    }

    public Quayaccessibilityadaptions withNarrowestpassagewidth(BigDecimal value) {
        setNarrowestpassagewidth(value);
        return this;
    }

    public Quayaccessibilityadaptions withFulllengthguideline(Boolean value) {
        setFulllengthguideline(value);
        return this;
    }

    public Quayaccessibilityadaptions withGuidelinestopplaceconnection(Boolean value) {
        setGuidelinestopplaceconnection(value);
        return this;
    }

    public Quayaccessibilityadaptions withTactilegroundsurfaceindicator(Boolean value) {
        setTactilegroundsurfaceindicator(value);
        return this;
    }

    public Quayaccessibilityadaptions withRamp(Boolean value) {
        setRamp(value);
        return this;
    }

    public Quayaccessibilityadaptions withRamplength(BigDecimal value) {
        setRamplength(value);
        return this;
    }

    public Quayaccessibilityadaptions withHeightwithenvironment(BigDecimal value) {
        setHeightwithenvironment(value);
        return this;
    }

    public Quayaccessibilityadaptions withRampwidth(BigDecimal value) {
        setRampwidth(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
