//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.time.ZonedDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import com.maestronic.gtfs.util.ZonedDateTimeISO8601XmlAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}validfrom"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stopsign"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}audiobutton"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stopsigntype" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}shelter" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}shelterpublicity" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}illuminatedstop" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}seatavailable" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}leantosupport" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}timetableinformation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}infounit" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}routenetworkmap" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}passengerinformationdisplay" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}passengerinformationdisplaytype" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}bicycleparking" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}numberofbicycleplaces" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}bins" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ovccico" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ovccharging" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validfrom",
    "stopsign",
    "audiobutton",
    "mutationdate",
    "stopsigntype",
    "shelter",
    "shelterpublicity",
    "illuminatedstop",
    "seatavailable",
    "leantosupport",
    "timetableinformation",
    "infounit",
    "routenetworkmap",
    "passengerinformationdisplay",
    "passengerinformationdisplaytype",
    "bicycleparking",
    "numberofbicycleplaces",
    "bins",
    "ovccico",
    "ovccharging"
})
@XmlRootElement(name = "quayfacilities")
public class Quayfacilities {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime validfrom;
    protected boolean stopsign;
    protected boolean audiobutton;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime mutationdate;
    protected String stopsigntype;
    protected Boolean shelter;
    protected Boolean shelterpublicity;
    protected Boolean illuminatedstop;
    protected Boolean seatavailable;
    protected Boolean leantosupport;
    protected Boolean timetableinformation;
    protected Boolean infounit;
    protected Boolean routenetworkmap;
    protected Boolean passengerinformationdisplay;
    protected String passengerinformationdisplaytype;
    protected Boolean bicycleparking;
    protected Integer numberofbicycleplaces;
    protected Boolean bins;
    protected Boolean ovccico;
    protected Boolean ovccharging;

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidfrom(ZonedDateTime value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the stopsign property.
     * 
     */
    public boolean isStopsign() {
        return stopsign;
    }

    /**
     * Sets the value of the stopsign property.
     * 
     */
    public void setStopsign(boolean value) {
        this.stopsign = value;
    }

    /**
     * Gets the value of the audiobutton property.
     * 
     */
    public boolean isAudiobutton() {
        return audiobutton;
    }

    /**
     * Sets the value of the audiobutton property.
     * 
     */
    public void setAudiobutton(boolean value) {
        this.audiobutton = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(ZonedDateTime value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the stopsigntype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopsigntype() {
        return stopsigntype;
    }

    /**
     * Sets the value of the stopsigntype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopsigntype(String value) {
        this.stopsigntype = value;
    }

    /**
     * Gets the value of the shelter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShelter() {
        return shelter;
    }

    /**
     * Sets the value of the shelter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShelter(Boolean value) {
        this.shelter = value;
    }

    /**
     * Gets the value of the shelterpublicity property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShelterpublicity() {
        return shelterpublicity;
    }

    /**
     * Sets the value of the shelterpublicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShelterpublicity(Boolean value) {
        this.shelterpublicity = value;
    }

    /**
     * Gets the value of the illuminatedstop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIlluminatedstop() {
        return illuminatedstop;
    }

    /**
     * Sets the value of the illuminatedstop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIlluminatedstop(Boolean value) {
        this.illuminatedstop = value;
    }

    /**
     * Gets the value of the seatavailable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSeatavailable() {
        return seatavailable;
    }

    /**
     * Sets the value of the seatavailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSeatavailable(Boolean value) {
        this.seatavailable = value;
    }

    /**
     * Gets the value of the leantosupport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLeantosupport() {
        return leantosupport;
    }

    /**
     * Sets the value of the leantosupport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLeantosupport(Boolean value) {
        this.leantosupport = value;
    }

    /**
     * Gets the value of the timetableinformation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTimetableinformation() {
        return timetableinformation;
    }

    /**
     * Sets the value of the timetableinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimetableinformation(Boolean value) {
        this.timetableinformation = value;
    }

    /**
     * Gets the value of the infounit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInfounit() {
        return infounit;
    }

    /**
     * Sets the value of the infounit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInfounit(Boolean value) {
        this.infounit = value;
    }

    /**
     * Gets the value of the routenetworkmap property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRoutenetworkmap() {
        return routenetworkmap;
    }

    /**
     * Sets the value of the routenetworkmap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRoutenetworkmap(Boolean value) {
        this.routenetworkmap = value;
    }

    /**
     * Gets the value of the passengerinformationdisplay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPassengerinformationdisplay() {
        return passengerinformationdisplay;
    }

    /**
     * Sets the value of the passengerinformationdisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPassengerinformationdisplay(Boolean value) {
        this.passengerinformationdisplay = value;
    }

    /**
     * Gets the value of the passengerinformationdisplaytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassengerinformationdisplaytype() {
        return passengerinformationdisplaytype;
    }

    /**
     * Sets the value of the passengerinformationdisplaytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassengerinformationdisplaytype(String value) {
        this.passengerinformationdisplaytype = value;
    }

    /**
     * Gets the value of the bicycleparking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBicycleparking() {
        return bicycleparking;
    }

    /**
     * Sets the value of the bicycleparking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBicycleparking(Boolean value) {
        this.bicycleparking = value;
    }

    /**
     * Gets the value of the numberofbicycleplaces property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberofbicycleplaces() {
        return numberofbicycleplaces;
    }

    /**
     * Sets the value of the numberofbicycleplaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberofbicycleplaces(Integer value) {
        this.numberofbicycleplaces = value;
    }

    /**
     * Gets the value of the bins property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBins() {
        return bins;
    }

    /**
     * Sets the value of the bins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBins(Boolean value) {
        this.bins = value;
    }

    /**
     * Gets the value of the ovccico property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOvccico() {
        return ovccico;
    }

    /**
     * Sets the value of the ovccico property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOvccico(Boolean value) {
        this.ovccico = value;
    }

    /**
     * Gets the value of the ovccharging property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOvccharging() {
        return ovccharging;
    }

    /**
     * Sets the value of the ovccharging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOvccharging(Boolean value) {
        this.ovccharging = value;
    }

    public Quayfacilities withValidfrom(ZonedDateTime value) {
        setValidfrom(value);
        return this;
    }

    public Quayfacilities withStopsign(boolean value) {
        setStopsign(value);
        return this;
    }

    public Quayfacilities withAudiobutton(boolean value) {
        setAudiobutton(value);
        return this;
    }

    public Quayfacilities withMutationdate(ZonedDateTime value) {
        setMutationdate(value);
        return this;
    }

    public Quayfacilities withStopsigntype(String value) {
        setStopsigntype(value);
        return this;
    }

    public Quayfacilities withShelter(Boolean value) {
        setShelter(value);
        return this;
    }

    public Quayfacilities withShelterpublicity(Boolean value) {
        setShelterpublicity(value);
        return this;
    }

    public Quayfacilities withIlluminatedstop(Boolean value) {
        setIlluminatedstop(value);
        return this;
    }

    public Quayfacilities withSeatavailable(Boolean value) {
        setSeatavailable(value);
        return this;
    }

    public Quayfacilities withLeantosupport(Boolean value) {
        setLeantosupport(value);
        return this;
    }

    public Quayfacilities withTimetableinformation(Boolean value) {
        setTimetableinformation(value);
        return this;
    }

    public Quayfacilities withInfounit(Boolean value) {
        setInfounit(value);
        return this;
    }

    public Quayfacilities withRoutenetworkmap(Boolean value) {
        setRoutenetworkmap(value);
        return this;
    }

    public Quayfacilities withPassengerinformationdisplay(Boolean value) {
        setPassengerinformationdisplay(value);
        return this;
    }

    public Quayfacilities withPassengerinformationdisplaytype(String value) {
        setPassengerinformationdisplaytype(value);
        return this;
    }

    public Quayfacilities withBicycleparking(Boolean value) {
        setBicycleparking(value);
        return this;
    }

    public Quayfacilities withNumberofbicycleplaces(Integer value) {
        setNumberofbicycleplaces(value);
        return this;
    }

    public Quayfacilities withBins(Boolean value) {
        setBins(value);
        return this;
    }

    public Quayfacilities withOvccico(Boolean value) {
        setOvccico(value);
        return this;
    }

    public Quayfacilities withOvccharging(Boolean value) {
        setOvccharging(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
