//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.time.ZonedDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import com.maestronic.gtfs.util.ZonedDateTimeISO8601XmlAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}validfrom"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}timetableinformation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}passengerinformationdisplay" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}passengerinformationdisplaytype" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}environmentinfo" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}bicycleparking" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}numberofbicycleplaces" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}toiletfacility" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ptbikerental" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}bins" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ovccico" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ovccharging" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validfrom",
    "mutationdate",
    "timetableinformation",
    "passengerinformationdisplay",
    "passengerinformationdisplaytype",
    "environmentinfo",
    "bicycleparking",
    "numberofbicycleplaces",
    "toiletfacility",
    "ptbikerental",
    "bins",
    "ovccico",
    "ovccharging"
})
@XmlRootElement(name = "stopplacefacilities")
public class Stopplacefacilities {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime validfrom;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime mutationdate;
    protected Boolean timetableinformation;
    protected Boolean passengerinformationdisplay;
    protected String passengerinformationdisplaytype;
    protected Boolean environmentinfo;
    protected Boolean bicycleparking;
    protected Integer numberofbicycleplaces;
    protected Boolean toiletfacility;
    protected Boolean ptbikerental;
    protected Boolean bins;
    protected Boolean ovccico;
    protected Boolean ovccharging;

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidfrom(ZonedDateTime value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(ZonedDateTime value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the timetableinformation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTimetableinformation() {
        return timetableinformation;
    }

    /**
     * Sets the value of the timetableinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimetableinformation(Boolean value) {
        this.timetableinformation = value;
    }

    /**
     * Gets the value of the passengerinformationdisplay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPassengerinformationdisplay() {
        return passengerinformationdisplay;
    }

    /**
     * Sets the value of the passengerinformationdisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPassengerinformationdisplay(Boolean value) {
        this.passengerinformationdisplay = value;
    }

    /**
     * Gets the value of the passengerinformationdisplaytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassengerinformationdisplaytype() {
        return passengerinformationdisplaytype;
    }

    /**
     * Sets the value of the passengerinformationdisplaytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassengerinformationdisplaytype(String value) {
        this.passengerinformationdisplaytype = value;
    }

    /**
     * Gets the value of the environmentinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnvironmentinfo() {
        return environmentinfo;
    }

    /**
     * Sets the value of the environmentinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnvironmentinfo(Boolean value) {
        this.environmentinfo = value;
    }

    /**
     * Gets the value of the bicycleparking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBicycleparking() {
        return bicycleparking;
    }

    /**
     * Sets the value of the bicycleparking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBicycleparking(Boolean value) {
        this.bicycleparking = value;
    }

    /**
     * Gets the value of the numberofbicycleplaces property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberofbicycleplaces() {
        return numberofbicycleplaces;
    }

    /**
     * Sets the value of the numberofbicycleplaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberofbicycleplaces(Integer value) {
        this.numberofbicycleplaces = value;
    }

    /**
     * Gets the value of the toiletfacility property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isToiletfacility() {
        return toiletfacility;
    }

    /**
     * Sets the value of the toiletfacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToiletfacility(Boolean value) {
        this.toiletfacility = value;
    }

    /**
     * Gets the value of the ptbikerental property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPtbikerental() {
        return ptbikerental;
    }

    /**
     * Sets the value of the ptbikerental property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPtbikerental(Boolean value) {
        this.ptbikerental = value;
    }

    /**
     * Gets the value of the bins property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBins() {
        return bins;
    }

    /**
     * Sets the value of the bins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBins(Boolean value) {
        this.bins = value;
    }

    /**
     * Gets the value of the ovccico property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOvccico() {
        return ovccico;
    }

    /**
     * Sets the value of the ovccico property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOvccico(Boolean value) {
        this.ovccico = value;
    }

    /**
     * Gets the value of the ovccharging property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOvccharging() {
        return ovccharging;
    }

    /**
     * Sets the value of the ovccharging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOvccharging(Boolean value) {
        this.ovccharging = value;
    }

    public Stopplacefacilities withValidfrom(ZonedDateTime value) {
        setValidfrom(value);
        return this;
    }

    public Stopplacefacilities withMutationdate(ZonedDateTime value) {
        setMutationdate(value);
        return this;
    }

    public Stopplacefacilities withTimetableinformation(Boolean value) {
        setTimetableinformation(value);
        return this;
    }

    public Stopplacefacilities withPassengerinformationdisplay(Boolean value) {
        setPassengerinformationdisplay(value);
        return this;
    }

    public Stopplacefacilities withPassengerinformationdisplaytype(String value) {
        setPassengerinformationdisplaytype(value);
        return this;
    }

    public Stopplacefacilities withEnvironmentinfo(Boolean value) {
        setEnvironmentinfo(value);
        return this;
    }

    public Stopplacefacilities withBicycleparking(Boolean value) {
        setBicycleparking(value);
        return this;
    }

    public Stopplacefacilities withNumberofbicycleplaces(Integer value) {
        setNumberofbicycleplaces(value);
        return this;
    }

    public Stopplacefacilities withToiletfacility(Boolean value) {
        setToiletfacility(value);
        return this;
    }

    public Stopplacefacilities withPtbikerental(Boolean value) {
        setPtbikerental(value);
        return this;
    }

    public Stopplacefacilities withBins(Boolean value) {
        setBins(value);
        return this;
    }

    public Stopplacefacilities withOvccico(Boolean value) {
        setOvccico(value);
        return this;
    }

    public Stopplacefacilities withOvccharging(Boolean value) {
        setOvccharging(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
