//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import com.maestronic.gtfs.util.ZonedDateTimeISO8601XmlAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}validfrom"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}heightwithenvironment"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}environmentaccessroute" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}guidelineconnection" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ramp" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}ramplength" minOccurs="0"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}rampwidth" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validfrom",
    "heightwithenvironment",
    "mutationdate",
    "environmentaccessroute",
    "guidelineconnection",
    "ramp",
    "ramplength",
    "rampwidth"
})
@XmlRootElement(name = "stopplaceaccessibilityadaptions")
public class Stopplaceaccessibilityadaptions {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime validfrom;
    @XmlElement(required = true)
    protected BigDecimal heightwithenvironment;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime mutationdate;
    protected Boolean environmentaccessroute;
    protected Boolean guidelineconnection;
    protected Boolean ramp;
    protected BigDecimal ramplength;
    protected BigDecimal rampwidth;

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidfrom(ZonedDateTime value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the heightwithenvironment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeightwithenvironment() {
        return heightwithenvironment;
    }

    /**
     * Sets the value of the heightwithenvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeightwithenvironment(BigDecimal value) {
        this.heightwithenvironment = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(ZonedDateTime value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the environmentaccessroute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnvironmentaccessroute() {
        return environmentaccessroute;
    }

    /**
     * Sets the value of the environmentaccessroute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnvironmentaccessroute(Boolean value) {
        this.environmentaccessroute = value;
    }

    /**
     * Gets the value of the guidelineconnection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGuidelineconnection() {
        return guidelineconnection;
    }

    /**
     * Sets the value of the guidelineconnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGuidelineconnection(Boolean value) {
        this.guidelineconnection = value;
    }

    /**
     * Gets the value of the ramp property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRamp() {
        return ramp;
    }

    /**
     * Sets the value of the ramp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRamp(Boolean value) {
        this.ramp = value;
    }

    /**
     * Gets the value of the ramplength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRamplength() {
        return ramplength;
    }

    /**
     * Sets the value of the ramplength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRamplength(BigDecimal value) {
        this.ramplength = value;
    }

    /**
     * Gets the value of the rampwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRampwidth() {
        return rampwidth;
    }

    /**
     * Sets the value of the rampwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRampwidth(BigDecimal value) {
        this.rampwidth = value;
    }

    public Stopplaceaccessibilityadaptions withValidfrom(ZonedDateTime value) {
        setValidfrom(value);
        return this;
    }

    public Stopplaceaccessibilityadaptions withHeightwithenvironment(BigDecimal value) {
        setHeightwithenvironment(value);
        return this;
    }

    public Stopplaceaccessibilityadaptions withMutationdate(ZonedDateTime value) {
        setMutationdate(value);
        return this;
    }

    public Stopplaceaccessibilityadaptions withEnvironmentaccessroute(Boolean value) {
        setEnvironmentaccessroute(value);
        return this;
    }

    public Stopplaceaccessibilityadaptions withGuidelineconnection(Boolean value) {
        setGuidelineconnection(value);
        return this;
    }

    public Stopplaceaccessibilityadaptions withRamp(Boolean value) {
        setRamp(value);
        return this;
    }

    public Stopplaceaccessibilityadaptions withRamplength(BigDecimal value) {
        setRamplength(value);
        return this;
    }

    public Stopplaceaccessibilityadaptions withRampwidth(BigDecimal value) {
        setRampwidth(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
