//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.time.ZonedDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import com.maestronic.gtfs.util.ZonedDateTimeISO8601XmlAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}validfrom"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}disabledaccessible"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stepFreeAccess"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}wheelchairAccess"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validfrom",
    "disabledaccessible",
    "stepFreeAccess",
    "wheelchairAccess",
    "mutationdate"
})
@XmlRootElement(name = "stopplacedisabledaccessibility")
public class Stopplacedisabledaccessibility {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime validfrom;
    @XmlElement(required = true)
    protected String disabledaccessible;
    @XmlElement(required = true)
    protected LimitationStatusEnum stepFreeAccess;
    @XmlElement(required = true)
    protected LimitationStatusEnum wheelchairAccess;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime mutationdate;

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidfrom(ZonedDateTime value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the disabledaccessible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisabledaccessible() {
        return disabledaccessible;
    }

    /**
     * Sets the value of the disabledaccessible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisabledaccessible(String value) {
        this.disabledaccessible = value;
    }

    /**
     * Gets the value of the stepFreeAccess property.
     * 
     * @return
     *     possible object is
     *     {@link LimitationStatusEnum }
     *     
     */
    public LimitationStatusEnum getStepFreeAccess() {
        return stepFreeAccess;
    }

    /**
     * Sets the value of the stepFreeAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitationStatusEnum }
     *     
     */
    public void setStepFreeAccess(LimitationStatusEnum value) {
        this.stepFreeAccess = value;
    }

    /**
     * Gets the value of the wheelchairAccess property.
     * 
     * @return
     *     possible object is
     *     {@link LimitationStatusEnum }
     *     
     */
    public LimitationStatusEnum getWheelchairAccess() {
        return wheelchairAccess;
    }

    /**
     * Sets the value of the wheelchairAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitationStatusEnum }
     *     
     */
    public void setWheelchairAccess(LimitationStatusEnum value) {
        this.wheelchairAccess = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(ZonedDateTime value) {
        this.mutationdate = value;
    }

    public Stopplacedisabledaccessibility withValidfrom(ZonedDateTime value) {
        setValidfrom(value);
        return this;
    }

    public Stopplacedisabledaccessibility withDisabledaccessible(String value) {
        setDisabledaccessible(value);
        return this;
    }

    public Stopplacedisabledaccessibility withStepFreeAccess(LimitationStatusEnum value) {
        setStepFreeAccess(value);
        return this;
    }

    public Stopplacedisabledaccessibility withWheelchairAccess(LimitationStatusEnum value) {
        setWheelchairAccess(value);
        return this;
    }

    public Stopplacedisabledaccessibility withMutationdate(ZonedDateTime value) {
        setMutationdate(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
