//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.21 at 04:29:49 PM SGT 
//


package nl.connekt.bison.chb;

import java.time.ZonedDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.maestronic.gtfs.util.OmitNullsToStringStyle;
import com.maestronic.gtfs.util.ZonedDateTimeISO8601XmlAdapter;
import org.apache.commons.lang3.builder.ToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stopplaceimagedate"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stopplaceimageurl"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}stopplaceimagedescription"/&gt;
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg}mutationdate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stopplaceimagedate",
    "stopplaceimageurl",
    "stopplaceimagedescription",
    "mutationdate"
})
@XmlRootElement(name = "stopplacephotodata")
public class Stopplacephotodata {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime stopplaceimagedate;
    @XmlElement(required = true)
    protected String stopplaceimageurl;
    @XmlElement(required = true)
    protected String stopplaceimagedescription;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(ZonedDateTimeISO8601XmlAdapter.class)
    protected ZonedDateTime mutationdate;

    /**
     * Gets the value of the stopplaceimagedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getStopplaceimagedate() {
        return stopplaceimagedate;
    }

    /**
     * Sets the value of the stopplaceimagedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopplaceimagedate(ZonedDateTime value) {
        this.stopplaceimagedate = value;
    }

    /**
     * Gets the value of the stopplaceimageurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopplaceimageurl() {
        return stopplaceimageurl;
    }

    /**
     * Sets the value of the stopplaceimageurl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopplaceimageurl(String value) {
        this.stopplaceimageurl = value;
    }

    /**
     * Gets the value of the stopplaceimagedescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopplaceimagedescription() {
        return stopplaceimagedescription;
    }

    /**
     * Sets the value of the stopplaceimagedescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopplaceimagedescription(String value) {
        this.stopplaceimagedescription = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public ZonedDateTime getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutationdate(ZonedDateTime value) {
        this.mutationdate = value;
    }

    public Stopplacephotodata withStopplaceimagedate(ZonedDateTime value) {
        setStopplaceimagedate(value);
        return this;
    }

    public Stopplacephotodata withStopplaceimageurl(String value) {
        setStopplaceimageurl(value);
        return this;
    }

    public Stopplacephotodata withStopplaceimagedescription(String value) {
        setStopplaceimagedescription(value);
        return this;
    }

    public Stopplacephotodata withMutationdate(ZonedDateTime value) {
        setMutationdate(value);
        return this;
    }

    /**
     * Generates a String representation of the contents of this type.
     * This is an extension method, produced by the 'ts' xjc plugin
     * 
     */
    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, OmitNullsToStringStyle.INSTANCE);
    }

}
